### ISSUE TITLE
Missing arrify dependency

### ISSUE THREAD

**Issue by u873838** [sonofmagic/graphql-depth-limit-ts#1]
arrify should be listed as a dependency, not devDependency.

**Comment by sonofmagic** [comment]
Hi, I should explain this. in [graphql-depth-limit](https://www.npmjs.com/package/graphql-depth-limit), it depends on `arrify`.
In this package, I use `rollup` to build `cjs` and `esm` format, and  `arrify` is resolved in dist code:


<img width="787" alt="QQ20230518-235358@2x" src="https://github.com/sonofmagic/graphql-depth-limit-ts/assets/15621541/80257830-2645-4eee-8bd0-e442519db500">


https://www.npmjs.com/package/graphql-depth-limit-ts?activeTab=code

so, there is no need to put `arrify` in dependency list.
